version: "3"
services:
  linux:
    container_name: "ubuntu-linux"
    image: "ubuntu"
    restart: "always"
    tty: true
    ports:
      - "443:443"
      - "2000-2020:2000-2020"
      - "10000-10100:10000-10100"
    volumes:
      - "./:/usr/src/"

