version: "3"
services:
  linux:
    container_name: "ubuntu-linux"
    image: "ubuntu"
    restart: "always"
    tty: true
    command: bash -c "cd /usr/src/ && npm start"
    ports:
      - "443:443"
      - "2000-2040:2000-2040"
      - "10000-10100:10000-10100"
    volumes:
      - "./:/usr/src/"

